services:
  ai-server:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    env_file: .env
    command:
      - redis-server
      - --requirepass
      - "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
